version: "3"
services:
  nodejs:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345*
      POSTGRES_USER: postgres
      POSTGRES_DB: db_konecta
